on:
  push:
    branches:  
      - main
jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.0.0
        
      - name: Authenticate Dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Dockerfile Build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-resume:latest . 

      - name: Dockerhub Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-resume:latest
